Repository laminas/laminas-cache-storage-adapter-test, pull requests merged in 2021-04, with the labels that each got.

#7 Adopt Laminas CI Workflow and add tests
  .gitattributes
  .github/workflows/continuous-integration.yml
  README.md
  composer.json
  src/AbstractAdapterTest.php
  src/AdapterOptionsTest.php
  src/CommonAdapterTest.php
  test/CommonAdapterTestTest.php
  test/TestAsset/MockAdapter.php
Labels: Enhancement

#8 Fixes workflow status badge
  README.md
Labels: Bug

#10 Align GHA CI workflow
  .gitignore
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
Labels: Enhancement

#12 fix markdown files
  README.md
  docs/book/v1/intro.md
Labels: Bug

#11 PHP 8 and Psalm support
  .gitignore
  composer.json
  composer.lock
  phpcs.xml
  phpunit.xml.dist
  psalm-baseline.xml
  psalm.xml.dist
  src/AbstractAdapterTest.php
  src/AbstractCommonAdapterTest.php
  src/AdapterOptionsTest.php
  src/CommonAdapterTest.php
  test/CommonAdapterTestTest.php
  test/TestAsset/MockAdapter.php
Labels: Enhancement

#13 bugfix: do not overwrite php datatypes
  src/CommonAdapterTest.php
Labels: BC Break, Bug
